apps/console/components/modals/manageOpPipelines.tsx
apps/console/deno.lock
apps/console/islands/drawer/infoDrawer.tsx
apps/console/islands/drawer/operation.tsx
apps/console/routes/notifications/index.tsx
apps/console/routes/pipelines/index.tsx

remove pipeline dropdown

---

apps/console/components/pipeline/notifications.tsx
apps/console/islands/drawer/tail.tsx
apps/console/islands/pipeline.tsx
apps/console/lib/mutation.ts
apps/console/routes/pipelines/add.tsx

...also some tail compare updates:

get pipeline notifications crud working

---

libs/wasm-transform/src/transform.rs

* Fix truncate length when using characters
* Remove validation for repcated value and path fields
* Fix test for character length truncate

Transform fixes

---

apps/console/islands/drawer/schema.tsx
apps/console/islands/drawer/tail.tsx
apps/console/islands/pipeline.tsx
apps/console/islands/pipelineTransform.tsx

swap tail before after

---

apps/console/components/form/inlineInput.tsx
apps/console/components/pipeline/pipelineMenu.tsx
apps/console/islands/pipeline.tsx
apps/console/routes/pipelines/[id]/delete.tsx

Also, fix delete bug when pipeline is new.

add a default step name when there is no step name

---

apps/console/components/serviceMap/serviceSignal.ts
apps/console/lib/fetch.ts
apps/console/lib/mutation.ts

Once `dselans/server-updates`, proto version can be updated here and this can be merged to main.
FYI, you can test against locally built protos like so, in deno.json:
`"streamdal-protos/": "../../libs/protos/build/ts/deno/"`

support setPipeline

---

apps/cli/docker-compose.yaml
docs/install/docker/docker-compose.yml
docs/install/ecs/ecs-private.yml
docs/install/ecs/ecs-public.yml
docs/install/helm/streamdal-server/templates/streamdal-console-deployment.yaml

Updated all install scripts and configs to use latest server & console docker images.
server:  `streamdal/server:0.0.16-40a202c`
console: `streamdal/console:0.0.19`

version updates in various install files

---

apps/console/components/form/formStringKV.tsx
apps/console/components/pipeline/headers.tsx
apps/console/components/pipeline/stepCondition.tsx
apps/console/components/pipeline/stepConditions.tsx
apps/console/fresh.gen.ts
apps/console/islands/pipeline.tsx
apps/console/islands/pipelineHTTP.tsx

There is some intelligence for url validation:

add http request step type

---

docs/install/ecs/ecs-private.yml
docs/install/ecs/ecs-public.yml
docs/install/helm/streamdal-server/Chart.yaml
docs/install/helm/streamdal-server/templates/streamdal-console-deployment.yaml
docs/install/helm/streamdal-server/values.yaml

@fritzstauff 
Latest server and console.

bumped versions

---

apps/console/components/serviceMap/serviceSignal.ts
apps/console/fresh.gen.ts
apps/console/islands/demo/http-request.tsx
apps/console/lib/audienceMetrics.ts
apps/console/lib/mutation.ts
apps/console/lib/sockets.ts
apps/console/lib/tail.ts
apps/console/routes/demo/http/echo.tsx
apps/console/routes/demo/http/index.tsx
apps/console/routes/ws/demo/http-request.tsx
apps/console/routes/ws/service-map.tsx

demo http request

---

.github/workflows/sdks-python-release.yml

commit was creating a new blank tag

---

.gitignore
apps/console/components/pipeline/pipelineMenu.tsx
apps/console/islands/drawer/infoDrawer.tsx
apps/console/islands/drawer/tail.tsx
apps/console/islands/notification.tsx
apps/console/islands/notifications.tsx
apps/console/islands/pipeline.tsx
apps/console/islands/pipelines.tsx
apps/console/lib/configs.ts
apps/console/routes/pipelines/save.tsx

I noticed the pipelines crud page was still slow, so adding move fixes for that.
Sorry there is a lot of reformatting noise in here.

more flowbite init dedupe

---

apps/console/islands/drawer/tail.tsx
apps/console/islands/pipeline.tsx
apps/console/islands/pipelineActionMenu.tsx
sdks/node/src/internal/pipeline.ts
sdks/node/src/internal/register.ts
sdks/node/src/internal/tail.ts

Also, I added a variety of tail fixes here for issues I discovered while working on the new web app demo.

pipeline name truncate and tooltip

---

apps/server/README.md
libs/wasm/inferschema/Cargo.lock

documenting server env vars

---

apps/docs/src/pages/en/core-components/sdk.mdx
apps/docs/src/pages/en/core-components/server.mdx
apps/docs/src/pages/en/guides/instrumentation.mdx

Included info about auth; included more info about server; included more info about SDKs.

expanded sdk and server docs

---

sdks/python/requirements.txt
sdks/python/setup.py

This includes the new PII matcher types

python-sdk: Bump protos version

---

.github/workflows/manual-versions-release.yml

cache for pip

---

.github/workflows/sdks-node-release.yml

We need to set the version after we do the pull.

also set version after pulling latest for node sdk

---

docs/install/helm/streamdal-server/templates/streamdal-console-service.yaml

Updates the streamdal server console name so that the ingress object and service object match.

Update streamdal console service name

---

sdks/go/go.mod
sdks/go/go.sum
sdks/go/go_sdk.go
sdks/go/go_sdk_test.go
sdks/go/register.go
sdks/go/wasm_test.go

* Implement new response format
* Deduping wasm data in SetPipelinesCommand

ENG-1690 - Dedup wasm module data

---

apps/console/islands/customNodes.tsx

Per Dan's ask I added multiple lines to the operation names for long names. I also went ahead and did the same for the service and component node since we've run into formatting issues with those as well.

support long names on nodes

---

sdks/node/src/index.ts

Adding `processJSON` and `processAny` to the Streamdal constructor.

Adding process functions to constructor

---

sdks/python/streamdal/__init__.py

* Incorrect spot, moved to correct WASM_EXIT_CODE_ERROR case and fixed incorrect log message

Fix errors counter

---

apps/server/services/store/helper.go
apps/server/services/store/store.go

This is needed for k8s operator.

added CreatedBy hack for audiences

---

apps/console/islands/nav.tsx
apps/console/islands/serviceDisplay.tsx
apps/console/routes/configs.tsx

Per Dan, remove the top level `configs` prop from the results.

hoist configs

---

apps/operator/Makefile
apps/operator/api/v1/streamdalconfig_types.go
apps/operator/config/crd/bases/crd.streamdal.com_streamdalconfigs.yaml
apps/operator/config/samples/crd_v1_streamdalconfig_empty.yaml
libs/wasm/custom/Cargo.lock

added markers for requiring certain fields.

added required fields

---

sdks/go/hostfunc/httprequest.go

* Fix empty body when emitting detective results
* If body is json and no request-type header has been specified, it will default to "application/json"
* Added 1s timeout to http requests
* When emitting detective results via http request, json is now snake-cased

gosdk: HTTPRequest() host function fixes

---

apps/log-processor/processor/processor.go

Reverts streamdal/streamdal#453

Revert "log-processor: Change message from string to bytes"

---

sdks/go/benchmarks_test.go
sdks/go/function.go
sdks/go/go_sdk.go
sdks/go/go_sdk_test.go
sdks/go/wasm_test.go

Expose WazeroExecutionModeCompiler and WazeroExecutionModeInterpreter

adds ability to configure wazero execution mode

---

apps/server/apis/grpcapi/grpcapi.go
apps/server/apis/httpapi/config.go
apps/server/apis/httpapi/httpapi.go
apps/server/main.go

exposes get config via http api

---

apps/docs/src/config.ts
apps/docs/src/pages/en/data-governance/compliance/hipaa.mdx

- fixed a broken link
- renamed a section

fixed broken link

---

apps/docs/src/pages/en/getting-started/how-streamdal-works.mdx

removed a wonky link on the "how streamdal works" page, added clarifying links.

clarification on docs page

---

sdks/python/requirements.txt
sdks/python/streamdal/hostfunc/__init__.py
sdks/python/test_wasm.py

* This method now receives a `WASMRequest` message instead of `HttpRequestStep`
* Added support for body mode
* This mirrors already existing changes to go-sdk

ENG-1747 - Update httpRequest host functions

---

sdks/ruby/.gitignore
sdks/ruby/Rakefile
sdks/ruby/init_wasm.sh
sdks/ruby/lib/hostfunc.rb
sdks/ruby/lib/streamdal.rb
sdks/ruby/lib/wasm_spec.rb

* Adds tests for wasm modules
* Fix more rubocop issues

Add WASM tests

---

apps/cli/README.md
apps/server/README.md
apps/server/services/kv/kv.go
apps/server/services/metrics/metrics.go
apps/server/util/util.go

* Re-added badge to readmes
* Fixed some ineffassigns

norelease: Fix goreportcard

---

apps/console/deno.json
apps/console/deno.lock

This is fix for opened issue https://github.com/streamdal/streamdal/issues/515
I will update my first PR right after!

hotfix: broken hash on dependency

---

apps/console/deno.lock
apps/console/islands/__tests__/nav.test.tsx
apps/console/islands/__tests__/notifications.test.tsx
apps/console/islands/__tests__/toasts.test.tsx
apps/console/islands/modals/__tests__/actionModal.test.tsx
apps/console/islands/modals/actionModal.tsx
apps/console/islands/nav.tsx
apps/console/islands/schema.tsx
apps/console/islands/tail.tsx
apps/console/islands/toasts.tsx

Hey guys, added some integration tests as promised before for components under islands.
Covered:
- nav
- notifications
- toasts
- modals
I am considering to also add tests to pipelines but that's for another PR, a lot of tricky moments in there that I had difficulties with
For coverage, it increased to 70 from 0, here is most recent report:
```
--------------------------------------------------------------------
File                                           | Branch % | Line % |
--------------------------------------------------------------------
components/error/custom.tsx                   |    100.0 |  100.0 |
components/error/internal.tsx                 |    100.0 |  100.0 |
components/error/server.tsx                   |    100.0 |  100.0 |
components/flowbite/init.tsx …
```

feat: adding integration tests
